"""add author to pitch db

Revision ID: d85e1b7ef777
Revises: 1a864bc2b7d8
Create Date: 2018-02-09 16:09:05.668894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85e1b7ef777'
down_revision = '1a864bc2b7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('body', sa.String(), nullable=True))
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=True))
    op.drop_column('pitch', 'pitch_body')
    op.drop_column('pitch', 'pitch_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('pitch_body', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'category')
    op.drop_column('pitch', 'body')
    op.drop_column('pitch', 'author')
    # ### end Alembic commands ###
